---
- hosts: all
  become: yes  
  tasks:
  - name: Update Root user's Password
    user:
      name: root
      update_password: always
      password: "{{ 'passwordsaresecret' | password_hash('sha512') }}"