---
- hosts: all
  become: yes  
  tasks:
  - name: Update Root user's Password
    user:
      name: isofh
      update_password: always
      password: "{{ '@5y8uwlG6kQrqwNvvhqJu&$F9xs#' | password_hash('sha512') }}"